### ISSUE TITLE
Sectionlar ust uste

### ISSUE THREAD

**Issue by samirkarimov** [GunaySemedli/PragmatechFoundationProject#4]
![Screenshot_3](https://user-images.githubusercontent.com/24611841/102398867-46132b00-3ff9-11eb-8e37-2ce3c2571756.jpg)
Sectionlar ic ice girib ona nezaret et

**Comment by GunaySemedli** [comment]
mende duzgun gorsedir.baxin duzeldi ?

**Comment by samirkarimov** [comment]
indi duzelib gunay
